SHELL := bash
.SHELLFLAGS := -euo pipefail -c
.DEFAULT_GOAL := test

####################################################################################################

LIBSCID_BUILD_ROOT ?= $(LIBSCID_ROOT)_build/

LIBSCID_CMAKE ?= cmake
LIBSCID_CTEST ?= ctest
LIBSCID_UV ?= uv
LIBSCID_TOX ?= tox

LIBSCID_CMAKE_BUILD_TYPE ?= Release
LIBSCID_CMAKE_BUILD_ARGS ?=
LIBSCID_CMAKE_CONFIGURE_ARGS ?=
LIBSCID_CMAKE_GENERATOR ?=
LIBSCID_CMAKE_C_COMPILER ?= $(LIBSCID_C_COMPILER)
LIBSCID_CMAKE_CXX_COMPILER ?= $(LIBSCID_CXX_COMPILER)

libscid.cmake.generator.arg := $(if $(LIBSCID_CMAKE_GENERATOR),-G "$(LIBSCID_CMAKE_GENERATOR)")

####################################################################################################

libscid.host.system := $(shell uname -s 2>/dev/null || echo Windows)

ifeq ($(libscid.host.system),Darwin)
libscid.library.name := libscid.dylib
else ifneq ($(filter MINGW% MSYS% CYGWIN%,$(libscid.host.system)),)
libscid.library.name := scid.dll
else
libscid.library.name := libscid.so
endif

####################################################################################################
