[tox]
requires =
    tox>=4.0
    tox-uv>=1.0
env_list = py

[testenv]
runner = uv-venv-runner
package = editable
dependency_groups = dev
commands =
    pytest {posargs:../../../tests/bindings/python}
