name: qc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  qc__format:
    name: qc__format
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Set up libscid toolchain
        uses: ./.github/actions/setup-libscid-toolchain
        with:
          make: "true"
          uv: "true"
          llvm: "true"
          clang_format: "true"

      - name: Check formatting
        run: make LIBSCID_CMAKE_BUILD_ARGS=--verbose libscid.qc-format

  qc__static-analysis:
    name: qc__static-analysis
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Set up libscid toolchain
        uses: ./.github/actions/setup-libscid-toolchain
        with:
          make: "true"
          uv: "true"
          llvm: "true"
          cppcheck: "true"
          clang_tidy: "true"

      - name: Run static analysis
        run: make LIBSCID_CMAKE_BUILD_ARGS=--verbose libscid.qc-static-analysis

  qc__dynamic-analysis:
    name: qc__dynamic-analysis
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v7

      - name: Set up libscid toolchain
        uses: ./.github/actions/setup-libscid-toolchain
        with:
          make: "true"
          llvm: "true"

      - name: Run dynamic analysis
        run: make LIBSCID_CMAKE_BUILD_ARGS=--verbose libscid.qc-dynamic-analysis
