name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release-build:
    name: release/build
    uses: ./.github/workflows/release-build.yml

  release-publish-github:
    name: release/publish-github
    needs:
      - release-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Publish to GitHub
        uses: ./.github/actions/publish-github
        with:
          tag: ${{ github.ref_name }}

  release-publish-pypi:
    name: release/publish-pypi
    needs:
      - release-publish-github
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Publish to PyPI
        uses: ./.github/actions/publish-pypi
        with:
          tag: ${{ github.ref_name }}
