name: release/build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-build__unix:
    name: release-build__${{ matrix.asset_label }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            asset_label: linux
            build_sdist: "true"
            build_source_archive: "true"
          - os: macos-15
            asset_label: macos-arm
            build_sdist: "false"
            build_source_archive: "false"

    steps:
      - uses: actions/checkout@v7

      - name: Build and package release
        uses: ./.github/actions/build-unix
        with:
          target: libscid.release
          platform_label: ${{ matrix.asset_label }}
          is_release: "true"
          docs: "true"
          make_args: >-
            LIBSCID_PYTHON_BUILD_SDIST=${{ matrix.build_sdist }}
            LIBSCID_BUILD_SOURCE_ARCHIVE=${{ matrix.build_source_archive }}

  release-build__windoze:
    name: release-build__windoze
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v7

      - name: Build and package release
        uses: ./.github/actions/build-windoze
        with:
          target: libscid.release
          platform_label: windoze
          is_release: "true"
          docs: "true"
          make_args: >-
            LIBSCID_PYTHON_BUILD_SDIST=false
            LIBSCID_BUILD_SOURCE_ARCHIVE=false

