name: release/build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-build__unix:
    name: release-build__${{ matrix.asset_label }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            asset_label: linux
          - os: macos-15
            asset_label: macos-arm

    steps:
      - uses: actions/checkout@v7

      - name: Build and package release
        uses: ./.github/actions/build-unix
        with:
          target: libscid.release
          platform_label: ${{ matrix.asset_label }}
          is_release: "true"
          docs: "true"

  release-build__windoze:
    name: release-build__windoze
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v7

      - name: Build and package release
        uses: ./.github/actions/build-windoze
        with:
          target: libscid.release
          platform_label: windoze
          is_release: "true"
          docs: "true"
