name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release-build:
    name: release/build
    uses: ./.github/workflows/release-build.yml

  release-publish-github:
    name: release/publish-github
    needs:
      - release-build
    uses: ./.github/workflows/release-publish-github.yml
    secrets: inherit

  release-publish-pypi:
    name: release/publish-pypi
    needs:
      - release-publish-github
    uses: ./.github/workflows/release-publish-pypi.yml
    secrets: inherit
